export const PRODUCTS = {
    LOAD: 'PRODUCTS_LOAD',
    LOAD_SUCCESS: 'PRODUCTS_LOAD_SUCCESS',
    LOAD_FAIL: 'PRODUCTS_LOAD_FAIL',
};

export const ONEPRODUCT = {
    LOAD: 'PRODUCT_LOAD',
    LOAD_SUCCESS: 'PRODUCT_LOAD_SUCCESS',
    LOAD_FAIL: 'PRODUCT_LOAD_FAIL',
    DELETE_SUCCESS: 'PRODUCT_DELETE_SUCCESS',
    UPDATE_SUCCESS: 'PRODUCT_UPDATE_SUCCESS',
    POST_SUCCESS: 'PRODUCT_POST_SUCCESS',
};
